---
- name: start postgres container
  sudo: yes
  docker:
    hostname: postgres
    image: postgres
    name: postgres
  tags:
    - skip-physical-blimp


- name: start mailbox container
  sudo: yes
  docker:
    hostname: blimp-mailbox
    registry: "{{cloudfleet.registry}}"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-mailbox"
    name: mailbox
    volumes:
      - "/opt/cloudfleet/common/mails:/opt/cloudfleet/maildir"
    ports:
      - "127.0.0.1:30001:3000"

- name: start conduit container
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "conduit"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-conduit"
    name: "conduit"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"


- name: start musterroll container
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "musterroll"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-musterroll"
    name: "musterroll"
    volumes:
      - "/opt/cloudfleet/common/users:/opt/cloudfleet/data"
    ports:
      - "127.0.0.1:30002:80"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"
