---
- name: start postgres container
  sudo: yes
  docker:
    hostname: postgres
    image: postgres
    name: postgres
  tags:
    - skip-physical-blimp


- name: start mailbox container
  sudo: yes
  docker:
    hostname: blimp-mailbox
    registry: "{{cloudfleet.registry}}"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-mailbox"
    name: mailbox
    volumes:
      - "/opt/cloudfleet/common/mails:/opt/cloudfleet/maildir"
    ports:
      - "30001:3000"

- name: start conduit container
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "conduit"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-conduit"
    name: "conduit"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/cloudfleet/conf:/opt/cloudfleet/conf"
    env:
      CLOUDFLEET_DOMAIN: "{{cloudfleet.domain}}"
      CLOUDFLEET_REGISTRY: "{{cloudfleet.registry}}"

- name: start musterroll container
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "musterroll"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-musterroll"
    name: "musterroll"
    volumes:
      - "/opt/cloudfleet/common/users:/opt/cloudfleet/data"
    ports:
      - "30002:80"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"
    links:
      - "conduit:blimp-docker"


- name: start nginx container
  sudo: yes
  docker:
    hostname: blimp-nginx
    registry: "{{cloudfleet.registry}}"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-nginx"
    name: nginx
    volumes:
      - "/opt/cloudfleet/conf/nginx:/opt/cloudfleet/conf/nginx"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      blimp-docker-host: {{{ansible_docker0.ipv4.address}}}}
