---
- name: run mailpile containers
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "mailpile-{{item.key}}"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-mailpile"
    name: "mailpile-{{item.key}}"
    links:
      - "doveshed"
    volumes:
      - "/opt/cloudfleet/data/shared/gnupg/{{item.key}}:/root/.gnupg"
      - "/opt/cloudfleet/data/shared/mails/{{item.key}}:/opt/cloudfleet/Mails"
      - "/opt/cloudfleet/data/apps/mailpile/{{item.key}}:/root/.local/share/Mailpile"
    ports:
      - "{{ports['mailpile-' + item.key]}}:33411"
    env:
      - "CLOUDFLEET_USERNAME={{item.key}}"
  with_dict: users
