---
- debug: var=cloudfleet
- name: run mailpile containers
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "mailpile-{{item.key}}"
    image: "{{cloudfleet.registry}}/cloudfleet/blimp-mailpile"
    name: "mailpile-{{item.key}}"
    #links: "{{item.value.dependencies|default('postgres')}}"
    volumes:
      - "/opt/cloudfleet/common/gnupg/{{item.key}}/:/root/.gnupg"
      - "/opt/cloudfleet/apps/mailpile/{{item.key}}/data/:/root/.local/share/Mailpile"
      - "/opt/cloudfleet/common/mails/{{item.key}}/:/opt/cloudfleet/Mails"
    ports:
      - "{{ports['mailpile-' + item.key]}}:33411"
    env: "CLOUDFLEET_USERNAME={{item.key}}"
  with_dict: users
