- name: install nodejs stuff
  apt: pkg={{ item }} state=present
  with_items:
    - nodejs-legacy
    - npm

- name: install haraka
  npm: name=Haraka state=present global=yes
  
- name: clone doveshed 
  sudo: yes
  git: repo=https://github.com/cloudfleet/doveshed.git dest=/opt/cloudfleet/doveshed
  
- name: generate tls private key
  command: "openssl genrsa -out /opt/cloudfleet/doveshed/tls_key.pem 2048"
  
- name: extract public key
  command: "openssl rsa -pubout -in /opt/cloudfleet/doveshed/tls_key.pem -out /opt/cloudfleet/doveshed/tls_cert.pem"
  
- name: creating conduit queue directory
  sudo: yes
  file: path=/opt/cloudfleet/doveshed/queue owner=cloudfleet state=directory

- name: creating doveshed log directory
  sudo: yes
  file: path=/var/log/cloudfleet state=directory

- name: copy supervisord config file
  sudo: yes
  copy: src=supervisor-doveshed.conf dest=/etc/supervisor/conf.d/doveshed.conf

