---
- name: install_meta_compose | install pip via easy_install
  command: easy_install pip
  tags:
    - blimp
    - python
    - install
    - packages

- name: install_meta_compose | install meta-compose Python package
  pip: name={{ item }} state=latest
  with_items:
    - meta-compose
    - websocket-client
  tags:
    - blimp
    - python
    - install
    - packages

# - name: install_meta_compose | install requests Python package
#   pip: name=requests state=present # version=2.5.2
#   tags:
#     - blimp
#     - python
#     - install
#     - packages
