---
- name: install_docker | remove some weird cubox apt repo
  apt_repository:
    repo: 'deb http://repo.gbps.io/BSP:/Cubox-i/Debian_Jessie/ ./'
    state: absent
  tags:
    - blimp
    - install
    - packages

- name: install_docker | add Debian apt repository for Docker
  apt_repository:
    #repo: 'deb http://ftp.de.debian.org/debian sid main contrib non-free'
    repo: 'deb http://ftp.de.debian.org/debian stretch main contrib non-free'
    state: present
  tags:
   - blimp
   - install
   - packages

- name: install_docker | install docker package
  apt: name={{ item }} state=present
  with_items:
   - docker.io
   - cgroupfs-mount # explicit because https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1324678.html
   - python-docker
  tags:
   - blimp
   - install
   - packages

# just temporary as we transition away from experimental
- name: install_docker | remove Debian apt repository for Docker
  apt_repository:
    #repo: 'deb http://ftp.de.debian.org/debian experimental main'
    repo: 'deb http://ftp.de.debian.org/debian stretch main contrib non-free'
    state: absent
    update_cache: no
  tags:
   - blimp
   - install
   - packages

# just temporary as we transition away from experimental
- name: install_docker | remove Debian apt repository for Docker
  apt_repository:
    repo: 'deb http://ftp.de.debian.org/debian sid main contrib non-free'
    state: absent
  tags:
   - blimp
   - install
   - packages
