---
- name: schedule_upgrade | add crontab entry for the blimp upgrades
  cron:
    name: "upgrade blimp"
    hour: "{{ blimp.upgrade.hour }}" # "{{ marina.builder.schedule.build.hour }}"
    minute: "{{ blimp.upgrade.minute }}" # "{{ marina.builder.schedule.build.minute }}"
    # sleep between 10 and 99 minutes and do the upgrade
    job: "sleep ${RANDOM:0:2}m ; /opt/cloudfleet/engineroom/bin/upgrade-blimp.sh >> /opt/cloudfleet/data/logs/upgrade.log 2>&1'"
  tags:
    - blimp
    - schedule

- name: cron_start_containers | Start containers at boot via crontab 
  cron:
    name: "blimp container start at boot"
    special_time: "reboot"
    job: "/opt/cloudfleet/engineroom/bin/start-containers.sh >> /opt/cloudfleet/data/log/start-containers.log 2>&1"
  tags:
    - blimp
    - schedule
    
    