---
- name: run docker containers
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "{{item.key}}"
    image: "{{cloudfleet.registry}}/{{item.value.image}}"
    name: "{{item.key}}"
    #links: "{{item.value.dependencies|default('postgres')}}"
    volumes:
      - "/opt/cloudfleet/apps/{{item.key}}/data:/opt/cloudfleet/data"
      - "/opt/cloudfleet/apps/{{item.key}}/log:/opt/cloudfleet/log"
    ports:
      - "{{item.value.port}}:80"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"
  with_dict: apps
