---
- name: run docker containers
  sudo: yes
  docker:
    state: running
    registry: "{{cloudfleet.registry}}"
    hostname: "{{item.key}}"
    image: "{{cloudfleet.registry}}/{{item.value.image}}"
    name: "{{item.key}}"
    links:
      - musterroll
      - doveshed
    volumes:
      - "/opt/cloudfleet/data/apps/{{item.key}}:/opt/cloudfleet/data"
    ports:
      - "{{item.value.port}}:80"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"
  with_dict: apps
