---
- name: create cloudfleet config directory
  file: path=/opt/cloudfleet/conf/nginx state=directory

- name: create ssl directory
  file: path=/opt/cloudfleet/conf/nginx/ssl state=directory


- name: add mailbox nginx config file
  copy: src=blimp-mailbox dest=/opt/cloudfleet/conf/nginx/blimp-mailbox.conf

- name: add musterroll nginx config file
  copy: src=blimp-musterroll dest=/opt/cloudfleet/conf/nginx/blimp-musterroll.conf
