---
- name: regather facts to read docker bridge ip address
  action: setup

- name: unmount hosts file
  command: "umount /etc/hosts"
  ignore_errors: yes

- name: add localhost to hosts file
  lineinfile: "dest=/etc/hosts line='127.0.0.1 localhost blimp' state=present"

- name: add docker bridge to hosts file
  lineinfile: "dest=/etc/hosts line='{{ansible_docker0.ipv4.address}} blimp-docker' state=present"

- name: pull docker image for mailpile
  command: "docker pull cloudfleet/blimp-mailpile"
  tags:
    - docker-pull



- name: copy smtp proxy config file
  template: src=smtp_proxy.ini dest=/opt/cloudfleet/doveshed/config/smtp_proxy.ini

- name: copy host_list config file
  template: src=host_list dest=/opt/cloudfleet/doveshed/config/host_list

- name: copy me config file
  template: src=me dest=/opt/cloudfleet/doveshed/config/me

- name: generate doveshed tls keys
  command: "openssl req -x509 -days 2190 -nodes -newkey rsa:4096 -keyout /opt/cloudfleet/doveshed/config/tls_key.pem -out /opt/cloudfleet/doveshed/config/tls_cert.pem -subj /C=/ST=/L=/O=CloudFleet/OU=/CN={{cloudfleet.domain}}"

#- name: start supervisord
#  service: name=supervisor state=restarted

- name: restart supervisord
  command: "service supervisor restart"
  

- name: generate nginx ssl certificate-request
  command: "openssl req -x509 -nodes -newkey rsa:4096 -keyout /opt/cloudfleet/conf/nginx/ssl/tls_key.pem -out /opt/cloudfleet/conf/nginx/ssl/tls_req.pem -subj /C=/ST=/L=/O=CloudFleet/OU=/CN={{cloudfleet.domain}}"
#  generates: /opt/cloudfleet/conf/nginx/ssl/tls_key.pem

- name: start nginx
  service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

- name: configure pagekite - remove existing files
  file: path=/etc/pagekite.d/20_frontends.rc state=absent


- name: configure pagekite
  template: src=pagekite.conf dest=/etc/pagekite.d/10_account.rc

- name: start pagekite
  service: name=pagekite state=restarted

- name: start postgres container
  sudo: yes
  docker: 
    hostname: postgres
    image: postgres
    name: postgres


- name: start mailbox container
  sudo: yes
  docker:
    hostname: blimp-mailbox
    image: cloudfleet/blimp-mailbox
    name: mailbox
    volumes: 
      - "/opt/cloudfleet/common/mails:/opt/cloudfleet/maildir"
      - "/etc/hosts:/etc/hosts"
    ports:
      - "127.0.0.1:30001:3000"
      
- name: start musterroll container
  sudo: yes
  docker: 
    state: running
    hostname: "musterroll"
    image: "cloudfleet/blimp-musterroll"
    name: "musterroll"
    volumes: 
      - "/opt/cloudfleet/apps/musterroll/data:/opt/cloudfleet/data"
      - "/etc/hosts:/etc/hosts"
    ports:
      - "127.0.0.1:30002:80"
    env: "CLOUDFLEET_DOMAIN={{cloudfleet.domain}}"
  with_dict: apps

