---
- name: regather facts to read docker bridge ip address
  action: setup

- name: unmount hosts file
  command: "umount /etc/hosts"

- name: add localhost to hosts file
  lineinfile: "dest=/etc/hosts line='127.0.0.1 localhost blimp' state=present"

- name: add docker bridge to hosts file
  lineinfile: "dest=/etc/hosts line='{{ansible_docker0.ipv4.address}} blimp-docker' state=present"

- name: pull docker image for mailpile
  command: "docker pull cloudfleet/blimp-mailpile"

- name: copy smtp proxy config file
  template: src=smtp_proxy.ini dest=/opt/cloudfleet/doveshed/config/smtp_proxy.ini

- name: copy host_list config file
  template: src=host_list dest=/opt/cloudfleet/doveshed/config/host_list

- name: copy me config file
  template: src=me dest=/opt/cloudfleet/doveshed/config/me


- name: start supervisord
  service: name=supervisor state=restarted
  

- name: start nginx
  service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

- name: configure pagekite - remove existing files
  file: path=/etc/pagekite.d/20_frontends.rc state=absent


- name: configure pagekite
  template: src=pagekite.conf dest=/etc/pagekite.d/10_account.rc

- name: start pagekite
  service: name=pagekite state=restarted

- name: start postgres container
  sudo: yes
  docker: 
    hostname: postgres
    image: postgres
    name: postgres


- name: start mailbox container
  sudo: yes
  docker:
    hostname: blimp-mailbox
    image: cloudfleet/blimp-mailbox
    name: blimp-mailbox
    volumes: 
      - "/opt/cloudfleet/common/mails:/opt/cloudfleet/maildir"
      - "/etc/hosts:/etc/hosts"
    ports:
      - "127.0.0.1:30001:3000"

