---
- name: start supervisod
  service: name=supervisor state=started

#- name: start conduit
#  supervisorctl: name=conduit state=started

- name: start nginx
  service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

- name: configure pagekite
  file: path=/etc/pagekite.d/20_frontends.rc state=absent


- name: configure pagekite
  template: src=pagekite.conf dest=/etc/pagekite.d/10_account.rc

- name: start pagekite
  service: name=pagekite state=restarted

- name: start postgres container
  sudo: yes
  docker: 
    hostname: postgres
    image: postgres
    name: postgres

