---
- name: regather facts to read docker bridge ip address
  action: setup

- name: unmount hosts file
  command: "umount /etc/hosts"

- name: add localhost to hosts file
  lineinfile: "dest=/etc/hosts line='127.0.0.1 localhost' state=present"

- name: add docker bridge to hosts file
  lineinfile: "dest=/etc/hosts line='{{ansible_docker0.ipv4.address}} blimp-docker' state=present"

- name: start supervisord
  service: name=supervisor state=started

- name: start nginx
  service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

- name: configure pagekite
  file: path=/etc/pagekite.d/20_frontends.rc state=absent


- name: configure pagekite
  template: src=pagekite.conf dest=/etc/pagekite.d/10_account.rc

- name: start pagekite
  service: name=pagekite state=restarted

- name: start postgres container
  sudo: yes
  docker: 
    hostname: postgres
    image: postgres
    name: postgres

