---
- name: start nginx
  service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes
- name: start postgres container
  sudo: yes
  docker: 
    hostname: postgres
    image: postgres
    name: postgres

